import type { CardInput } from "./schema";

export function emptyCardInput(id: string): CardInput {
  return {
    id,
    slug: "",
    businessName: "",
    description: "",
    category: "",
    address: "",
    schedule: "",
    extraInfo: "",
    logoUrl: "",
    coverImageUrl: "",
    backgroundImageUrl: "",
    phone: "",
    whatsapp: "",
    whatsappMessage: "",
    instagramUrl: "",
    facebookUrl: "",
    googleMapsUrl: "",
    websiteUrl: "",
    bookingUrl: "",
    primaryColor: "#1e293b",
    secondaryColor: "#f1f5f9",
    backgroundColor: "#ffffff",
    textColor: "#0f172a",
    accentColor: "#2563eb",
    template: "modern",
    layoutVariant: "centered",
    actionsLayout: "stack",
    borderRadius: "md",
    buttonStyle: "solid",
    cardStyle: "flat",
    shadowStyle: "soft",
    logoSize: "md",
    logoShape: "circle",
    font: "inter",
    backgroundMode: "color",
    backgroundOverlay: 40,
    showQr: true,
    isActive: true,
    isPaid: false,
    buttons: [],
  };
}
